Repository juansrz/SI-Practica1-Grupo18, pull requests merged in 2025-03, with the labels that each got.

#4 Añade script de análisis de incidencias
  analisis.py
Labels: enhancement

#7 Actualización de los archivos de modelado
  Modelado_de_procesoBPMN.drawio
Labels: documentation

#6 Actualización de fecha cierre en BD main.py
  main.py
Labels: bug

#11 Creación de Web Flask
  app.py
  static/css/MIS.css
  static/images/BPMN.png
  static/images/SI.png
  static/images/UML.png
  static/images/actuaciones_empleado.png
  static/images/actuaciones_semana.png
  static/images/critical_clients.png
  static/images/tiempo_mant.png
  static/images/tipo_incidencia.png
  templates/index.html
  templates/resultados.html
Labels: enhancement

#12 Feature/graficos
  graficos.py
Labels: enhancement

#13 Fix analisis.py
  analisis.py
Labels: bug

#17 Versión 2 de memoria y PDF final
  Memoria_Practica1_SI_v2.docx
  Practica1_SI_GRUPO_18.pdf
Labels: documentation
